#!/usr/bin/env python3
"""
Update citation counts for all papers in the bibliography.

Uses the OpenAlex API (free, no key required) to fetch citation counts by DOI.
Updates both _data/citations.yml and the bib file entries.

Schedule: runs weekly via GitHub Actions.
"""

import re
import sys
import time
import json
import urllib.request
import urllib.parse
from pathlib import Path

# ── Configuration ──

REPO_ROOT = Path(__file__).resolve().parent.parent
BIB_FILE = REPO_ROOT / "_bibliography" / "papers.bib"
CITATIONS_FILE = REPO_ROOT / "_data" / "citations.yml"

OPENALEX_API = "https://api.openalex.org/works"
# Polite pool: provide email for faster rate limits
OPENALEX_EMAIL = "liji_xy@csu.edu.cn"


# ── Helpers ──

def extract_dois_from_bib():
    """Extract all DOIs and their bib keys from the .bib file."""
    text = BIB_FILE.read_text(encoding="utf-8")
    entries = []
    current_key = None
    current_doi = None

    for line in text.splitlines():
        # Match bib key
        key_match = re.match(r"@\w+\{(\S+),", line)
        if key_match:
            if current_key and current_doi:
                entries.append({"key": current_key, "doi": current_doi})
            current_key = key_match.group(1)
            current_doi = None
            continue

        # Match DOI
        doi_match = re.match(r"\s*doi\s*=\s*\{([^}]+)\}", line)
        if doi_match and current_key:
            current_doi = doi_match.group(1).strip()

    # Don't forget the last entry
    if current_key and current_doi:
        entries.append({"key": current_key, "doi": current_doi})

    return entries


def fetch_citation_count(doi):
    """Fetch citation count from OpenAlex API by DOI."""
    url = f"{OPENALEX_API}/https://doi.org/{urllib.parse.quote(doi, safe='')}"
    if OPENALEX_EMAIL:
        url += f"?mailto={OPENALEX_EMAIL}"

    try:
        req = urllib.request.Request(url, headers={"Accept": "application/json"})
        with urllib.request.urlopen(req, timeout=15) as resp:
            data = json.loads(resp.read())
            return data.get("cited_by_count", 0)
    except Exception as e:
        print(f"    Warning: could not fetch for {doi}: {e}")
        return None


def write_citations_yml(citations_data):
    """Write citation data to _data/citations.yml."""
    lines = []
    lines.append(f"# Auto-generated by update_citations.py")
    lines.append(f"# Do not edit manually — will be overwritten weekly")
    lines.append(f"")

    for entry in sorted(citations_data, key=lambda x: x.get("citations", 0), reverse=True):
        lines.append(f"{entry['key']}:")
        lines.append(f"  doi: \"{entry['doi']}\"")
        lines.append(f"  citations: {entry['citations']}")
        if entry.get("title"):
            # Escape quotes in title
            title = entry["title"].replace('"', '\\"')
            lines.append(f"  title: \"{title}\"")
        lines.append("")

    CITATIONS_FILE.write_text("\n".join(lines), encoding="utf-8")


def update_bib_citations(citations_map):
    """Update citation_count fields in the .bib file."""
    text = BIB_FILE.read_text(encoding="utf-8")
    updated = False

    for key, count in citations_map.items():
        # Check if citation_count field already exists for this entry
        # We look for the entry and either update or insert the field
        pattern = re.compile(
            r"(@\w+\{" + re.escape(key) + r",.*?)(citation_count\s*=\s*\{\d+\})",
            re.DOTALL
        )
        if pattern.search(text):
            # Update existing
            text = pattern.sub(lambda m: m.group(1) + f"citation_count={{{count}}}", text)
            updated = True
        else:
            # Insert before the closing brace of this entry
            entry_pattern = re.compile(
                r"(@\w+\{" + re.escape(key) + r",.*?)(  author_verified=\{[^}]*\},?\s*\})",
                re.DOTALL
            )
            match = entry_pattern.search(text)
            if match:
                text = text[:match.start(2)] + f"  citation_count={{{count}}},\n" + match.group(2) + text[match.end(2):]
                updated = True

    if updated:
        BIB_FILE.write_text(text, encoding="utf-8")

    return updated


# ── Main ──

def main():
    print("=" * 60)
    print("Citation Count Updater (via OpenAlex)")
    print("=" * 60)

    entries = extract_dois_from_bib()
    print(f"\nPapers with DOI: {len(entries)}")

    citations_data = []
    citations_map = {}
    updated_count = 0
    total = len(entries)

    for i, entry in enumerate(entries):
        doi = entry["doi"]
        key = entry["key"]
        print(f"  [{i+1}/{total}] {key}: ", end="", flush=True)

        count = fetch_citation_count(doi)
        if count is not None:
            print(f"{count} citations")
            citations_data.append({
                "key": key,
                "doi": doi,
                "citations": count,
            })
            citations_map[key] = count
            updated_count += 1
        else:
            print("skipped")

        # Rate limiting: ~10 requests per second (OpenAlex polite pool)
        time.sleep(0.12)

    print(f"\n{'=' * 60}")
    print(f"Updated {updated_count}/{total} papers")

    if not citations_data:
        print("No citation data retrieved.")
        return 0

    # Write citations.yml
    write_citations_yml(citations_data)
    print(f"Written to {CITATIONS_FILE.name}")

    # Update bib file
    bib_updated = update_bib_citations(citations_map)
    if bib_updated:
        print(f"Updated citation_count in {BIB_FILE.name}")

    # Summary stats
    total_citations = sum(e["citations"] for e in citations_data)
    top_papers = sorted(citations_data, key=lambda x: x["citations"], reverse=True)[:5]
    print(f"\nTotal citations: {total_citations}")
    print(f"\nTop 5 most cited:")
    for p in top_papers:
        print(f"  {p['citations']:>5}  {p['key']}")

    print(f"\n{'=' * 60}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
